CREATE TABLE `learning_activity_sessions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `sessionKey` varchar(64) NOT NULL,
  `userId` int,
  `studentEmail` varchar(320) NOT NULL,
  `orgId` int,
  `organizationMemberId` int,
  `teamFlexLicenceId` int,
  `courseKey` varchar(64) NOT NULL,
  `activityType` enum('quiz','mock_exam','flashcards','process_guide','ai_tutor') NOT NULL,
  `topic` varchar(128),
  `startedAt` timestamp NOT NULL DEFAULT (now()),
  `lastHeartbeatAt` timestamp NOT NULL DEFAULT (now()),
  `activeSeconds` int NOT NULL DEFAULT 0,
  `lastSequence` int NOT NULL DEFAULT 0,
  `unitsCompleted` int NOT NULL DEFAULT 0,
  `score` int,
  `total` int,
  `status` enum('active','completed','abandoned') NOT NULL DEFAULT 'active',
  `completedAt` timestamp,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `learning_activity_sessions_id` PRIMARY KEY(`id`),
  CONSTRAINT `learning_sessions_key_unique_idx` UNIQUE(`sessionKey`),
  INDEX `learning_sessions_identity_time_idx` (`studentEmail`,`startedAt`),
  INDEX `learning_sessions_org_time_idx` (`orgId`,`startedAt`),
  INDEX `learning_sessions_member_time_idx` (`organizationMemberId`,`startedAt`),
  INDEX `learning_sessions_flex_time_idx` (`teamFlexLicenceId`,`startedAt`),
  INDEX `learning_sessions_course_time_idx` (`courseKey`,`startedAt`)
);
--> statement-breakpoint
CREATE TABLE `training_attestations` (
  `id` int AUTO_INCREMENT NOT NULL,
  `reportId` varchar(64) NOT NULL,
  `orgId` int NOT NULL,
  `organizationMemberId` int,
  `teamFlexLicenceId` int,
  `operatorUserId` int,
  `operatorEmail` varchar(320) NOT NULL,
  `operatorName` varchar(200),
  `courseKey` varchar(64) NOT NULL,
  `periodStart` timestamp NOT NULL,
  `periodEnd` timestamp NOT NULL,
  `verifiedActiveSeconds` int NOT NULL,
  `studySessionCount` int NOT NULL,
  `providerName` varchar(200) NOT NULL DEFAULT 'Echelon Institute',
  `instructorName` varchar(200) NOT NULL,
  `instructorContact` varchar(320) NOT NULL,
  `trainingMethod` varchar(120) NOT NULL DEFAULT 'Interactive online training',
  `subjectSummary` text NOT NULL,
  `signedByName` varchar(200) NOT NULL,
  `signedByEmail` varchar(320) NOT NULL,
  `signedRole` varchar(100) NOT NULL,
  `signedAt` timestamp NOT NULL DEFAULT (now()),
  `digestSha256` varchar(64) NOT NULL,
  `snapshotJson` text NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `training_attestations_id` PRIMARY KEY(`id`),
  CONSTRAINT `training_attestations_report_unique_idx` UNIQUE(`reportId`),
  INDEX `training_attestations_org_time_idx` (`orgId`,`signedAt`),
  INDEX `training_attestations_operator_time_idx` (`operatorEmail`,`signedAt`)
);
