import { Download, FileCheck2, LogIn, Printer } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import SiteNav from "@/components/SiteNav";
import { trpc } from "@/lib/trpc";
import { usePageMeta } from "@/hooks/usePageMeta";

const hours = (seconds: number) => `${(Math.max(0, seconds) / 3600).toFixed(2)} h`;
const isoDate = (date: Date) => date.toISOString().slice(0, 10);
function download(csv: string, filename: string) { const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }

export default function TrainingHours() {
  usePageMeta({ title: "My Training Hours — Echelon Institute", description: "Your platform-recorded study record." });
  const [from, setFrom] = useState(() => isoDate(new Date(Date.now() - 365 * 24 * 60 * 60 * 1000)));
  const [to, setTo] = useState(() => isoDate(new Date()));
  const input = useMemo(() => ({ from: new Date(`${from}T00:00:00`), to: new Date(`${to}T23:59:59`) }), [from, to]);
  const summary = trpc.training.mySummary.useQuery(input, { retry: false });
  const csv = trpc.training.myCsv.useQuery(input, { enabled: false });
  const [exportError, setExportError] = useState("");
  if (summary.isLoading) return <div className="min-h-screen bg-slate-50"><SiteNav currentPath="/training-hours" /><main className="mx-auto max-w-5xl px-5 py-20 text-slate-600">Loading your study record…</main></div>;
  if (summary.isError || !summary.data) { const tooLarge = summary.error?.data?.code === "PAYLOAD_TOO_LARGE"; return <div className="min-h-screen bg-slate-50"><SiteNav currentPath="/training-hours" /><main className="mx-auto max-w-xl px-5 py-20 text-center"><LogIn className="mx-auto mb-5 h-10 w-10 text-blue-700" /><h1 className="text-3xl font-extrabold text-slate-900">{tooLarge ? "Choose a shorter reporting period" : "Verify your email to view your record"}</h1><p className="mt-3 text-slate-600">{tooLarge ? summary.error?.message : "Your training-hours record remains available after course access ends."}</p>{tooLarge ? <div className="mt-6 flex flex-wrap justify-center gap-3"><label className="text-xs font-bold">From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="ml-2 rounded-lg border p-2" /></label><label className="text-xs font-bold">To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="ml-2 rounded-lg border p-2" /></label></div> : <Link href="/account?next=/training-hours" className="mt-7 inline-flex rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">Sign in or restore access</Link>}</main></div>; }
  const data = summary.data;
  const exportCsv = async () => { const result = await csv.refetch(); if (result.data) { setExportError(""); download(result.data.csv, result.data.filename); } else if (result.error) setExportError(result.error.message); };
  return <div className="min-h-screen bg-slate-50 text-slate-900"><SiteNav currentPath="/training-hours" /><style>{`@media print { .training-hours-actions, nav, details { display:none!important; } .training-record { box-shadow:none!important; border:0!important; } body { background:#fff!important; } }`}</style><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
    <div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-extrabold uppercase tracking-[0.18em] text-blue-700">Platform-recorded study activity</div><h1 className="mt-2 text-3xl font-black">My Training Hours</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">A concise record of active time while you studied. Dates and individual session durations are available in the optional appendix.</p></div><div className="training-hours-actions flex flex-wrap items-end gap-2"><label className="text-xs font-bold">From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="ml-2 rounded-lg border p-2" /></label><label className="text-xs font-bold">To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="ml-2 rounded-lg border p-2" /></label><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold"><Printer className="h-4 w-4" />Save PDF</button><button onClick={exportCsv} disabled={csv.isFetching} className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white"><Download className="h-4 w-4" />{csv.isFetching ? "Preparing…" : "CSV detail"}</button></div></div>
    {exportError && <div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{exportError}</div>}
    <section className="training-record rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Platform-recorded time" value={hours(data.activeSeconds)} colour="blue" /><Metric label="Supervisor-review duration" value={hours(data.supervisorReview.supervisorReviewSeconds)} detail="Daily cap and quarter-hour floor applied" colour="green" /><Metric label="Study sessions" value={String(data.sessionCount)} /><Metric label="Record period" value={`${new Date(data.from).toLocaleDateString()} – ${new Date(data.to).toLocaleDateString()}`} /></div>
      <h2 className="mt-8 text-lg font-extrabold">By assigned course</h2>{data.byCourse.length === 0 ? <p className="mt-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">No study sessions are recorded yet. Timing begins after your first deliberate interaction during a signed-in study session.</p> : <div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200">{data.byCourse.map((course) => <div key={course.courseKey} className="flex items-center justify-between gap-4 p-4"><div><div className="font-bold">{course.courseName}</div><div className="text-xs text-slate-500">{course.sessionCount} sessions</div></div><div className="text-lg font-black text-blue-800">{hours(course.activeSeconds)}</div></div>)}</div>}
      <h2 className="mt-8 text-lg font-extrabold">Activity mix</h2><div className="mt-3 flex flex-wrap gap-2">{data.byActivity.map((activity) => <span key={activity.activityType} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-semibold">{activity.label}: {hours(activity.activeSeconds)}</span>)}</div>
      {data.attestations.length > 0 && <div className="mt-8"><h2 className="flex items-center gap-2 text-lg font-extrabold"><FileCheck2 className="h-5 w-5 text-emerald-700" />Signed records</h2><div className="mt-3 space-y-2">{data.attestations.map((record) => <Link key={record.reportId} href={`/training-hours/records/${record.reportId}`} className="block rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm hover:border-emerald-400"><div className="font-bold">{record.operatorName || record.operatorEmail} · {hours(record.platformRecordedSeconds)}</div><div className="mt-1 text-emerald-900">Signed by {record.signedByName} ({record.signedRole}) on {new Date(record.signedAt).toLocaleDateString()}</div><div className="mt-1 font-mono text-[10px] text-slate-500">Open immutable record {record.reportId}</div></Link>)}</div></div>}
    </section><details className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-extrabold">Session dates and durations ({data.sessions.length})</summary><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="py-2">Date</th><th>Course</th><th>Activity</th><th>Topic</th><th className="text-right">Duration</th></tr></thead><tbody>{data.sessions.map((session) => <tr key={session.sessionKey} className="border-b border-slate-100"><td className="py-3">{new Date(session.startedAt).toLocaleString()}</td><td>{session.courseKey}</td><td>{session.activityType.replaceAll("_", " ")}</td><td>{session.topic || "—"}</td><td className="text-right font-bold">{Math.round(session.activeSeconds / 60)} min</td></tr>)}</tbody></table></div></details><p className="mt-5 text-xs leading-relaxed text-slate-500">This page shows platform-recorded study time. The supervisor-review duration applies Ontario’s normal seven-hour daily cap and quarter-hour floor without deciding eligibility. The employer and regulator determine whether time qualifies as OJT or continuing-education credit.</p>
  </main></div>;
}
function Metric({ label, value, detail, colour = "slate" }: { label: string; value: string; detail?: string; colour?: "blue" | "green" | "slate" }) { const palette = colour === "blue" ? "bg-blue-50 text-blue-700" : colour === "green" ? "bg-emerald-50 text-emerald-700" : "bg-slate-50 text-slate-500"; return <div className={`rounded-xl p-5 ${palette}`}><div className="text-xs font-bold uppercase">{label}</div><div className="mt-2 text-3xl font-black text-slate-900">{value}</div>{detail && <p className="mt-1 text-[11px] text-emerald-900">{detail}</p>}</div>; }
