/**
 * Explicit Data Explorer column classifications. A schema column remains
 * unavailable until it is deliberately listed here and reviewed.
 */
export interface DataExplorerColumnClassification {
  readable: readonly string[];
  restricted: readonly string[];
}

export const DATA_EXPLORER_COLUMN_CLASSIFICATIONS: Record<string, DataExplorerColumnClassification> = {
  "users": { readable: ["id", "openId", "name", "email", "loginMethod", "role", "createdAt", "updatedAt", "lastSignedIn", "phone", "province"], restricted: [] },
  "student-profiles": { readable: ["id", "userId", "examType", "topicAccuracy", "weakTopics", "strongTopics", "totalAttempts", "totalSessions", "currentStreak", "longestStreak", "lastActiveDate", "updatedAt", "studentEmail"], restricted: [] },
  "learner-onboarding": { readable: ["id", "userId", "studentEmail", "orgId", "organizationMemberId", "courseKey", "examDate", "studyDaysPerWeek", "sessionMinutes", "confidence", "status", "diagnosticStartedAt", "completedAt", "createdAt", "updatedAt"], restricted: [] },
  "exam-dates": { readable: ["id", "email", "productKey", "examDate", "remindersSent", "createdAt", "updatedAt", "orgId", "organizationMemberId", "courseKey"], restricted: [] },
  "magic-links": { readable: ["id", "email", "examTypes", "expiresAt", "usedAt", "createdAt"], restricted: ["tokenHash"] },
  "dashboard-otps": { readable: ["id", "email", "expiresAt", "usedAt", "attempts", "createdAt"], restricted: ["codeHash"] },
  "email-otp-codes": { readable: ["id", "email", "expiresAt", "usedAt", "attempts", "createdAt"], restricted: ["codeHash"] },
  "purchases": { readable: ["id", "userId", "email", "productKey", "productName", "amountCAD", "createdAt", "utmSource", "utmMedium", "utmCampaign", "referralSource", "province", "phone", "customerName", "status", "accessExpiresAt", "refundedAt", "welcomeEmailSentAt"], restricted: ["stripeSessionId", "stripePaymentIntentId"] },
  "subscriptions": { readable: ["id", "userId", "email", "tier", "province", "status", "currentPeriodStart", "currentPeriodEnd", "amountCAD", "createdAt", "updatedAt", "orgId", "customerName", "phone", "utmSource", "utmMedium", "utmCampaign", "referralSource"], restricted: ["stripeSubscriptionId", "stripeCustomerId"] },
  "purchase-email-outbox": { readable: ["id", "status", "attempts", "availableAt", "sentAt", "createdAt"], restricted: ["stripeSessionId", "payload", "leaseToken"] },
  "stripe-event-log": { readable: ["id", "eventType", "orgId", "status", "dbProcessed", "emailDelivered", "attemptCount", "createdAt", "completedAt", "processingStartedAt"], restricted: ["stripeEventId", "stripeObjectId", "processingToken", "lastError"] },
  "organizations": { readable: ["id", "name", "province", "tier", "seatsTotal", "managerEmail", "termEnd", "billingType", "status", "createdAt", "stream", "termStart", "onboardingEmailSentAt"], restricted: ["stripeSubscriptionId", "stripeCustomerId"] },
  "organization-members": { readable: ["id", "orgId", "email", "role", "status", "assignedAt", "revokedAt", "name", "courseKey", "courseKeys", "lastRemindedAt", "reminderOptOut"], restricted: ["unsubscribeToken"] },
  "organization-term-usage": { readable: ["id", "orgId", "memberEmail", "termStart", "termEnd", "firstActivatedAt"], restricted: [] },
  "team-flex-orders": { readable: ["id", "organizationId", "purchaserUserId", "managerEmail", "totalLicences", "subtotalCents", "discountRate", "discountCents", "totalBeforeTaxCents", "taxCents", "totalPaidCents", "currency", "status", "overlapAcknowledged", "paidAt", "createdAt"], restricted: ["stripeCheckoutSessionId", "stripePaymentIntentId", "stripeCustomerId"] },
  "team-flex-order-items": { readable: ["id", "orderId", "courseKey", "examFamily", "pricingBand", "courseLevel", "termMonths", "quantity", "listUnitPriceCents", "discountRate", "discountedUnitPriceCents", "lineTotalCents", "createdAt"], restricted: [] },
  "team-flex-licences": { readable: ["id", "orderItemId", "organizationId", "courseKey", "termMonths", "status", "invitedEmail", "invitedAt", "operatorUserId", "assignedAt", "activatedAt", "accessEndsAt", "originalAccessEndsAt", "reportingEndsAt", "extensionApplied", "extensionStartsAt", "activationDeadline", "startsAt", "suspendedAt", "suspendedReason", "revokedAt", "revokeReason", "previousStatus", "replacedByLicenceId", "replacesLicenceId", "createdAt"], restricted: ["invitationToken"] },
  "team-flex-extensions": { readable: ["id", "licenceId", "organizationId", "purchaserUserId", "extensionDays", "priceCents", "status", "appliedAt", "newAccessEndsAt", "createdAt"], restricted: ["stripeCheckoutSessionId", "stripePaymentIntentId"] },
  "on-the-job-training": { readable: ["id", "orgId", "organizationMemberId", "studentEmail", "courseKey", "sessionDate", "topics", "learningObjectives", "providerName", "providerPhone", "durationHours", "structuredLearningConfirmed", "recordedByEmail", "createdAt", "updatedAt"], restricted: [] },
  "training-attestations": { readable: ["id", "reportId", "orgId", "organizationMemberId", "teamFlexLicenceId", "operatorUserId", "operatorEmail", "operatorName", "courseKey", "periodStart", "periodEnd", "platformRecordedSeconds", "supervisorReviewSeconds", "studySessionCount", "providerName", "instructorName", "instructorContact", "learningObjectives", "trainingMethod", "signedByName", "signedByEmail", "signedRole", "signerAuthority", "attestationKind", "signedAt", "createdAt"], restricted: ["subjectSummary", "snapshotJson", "digestSha256"] },
  "exam-outcomes": { readable: ["id", "orgId", "memberEmail", "courseKey", "result", "examDate", "recordedBy", "recordedAt", "readinessScoreAtOutcome", "readinessModelVersion"], restricted: [] },
  "ceu-learning-records": { readable: ["id", "courseKey", "courseVersion", "revision", "activeSeconds", "exerciseAttempts", "createdAt", "updatedAt"], restricted: ["studentEmail", "operatorNumber", "stateJson"] },
  "ceu-daily-time": { readable: ["localDate", "seconds", "lastCreditedAt"], restricted: ["studentEmail"] },
  "learning-activity-sessions": { readable: ["id", "sessionKey", "userId", "studentEmail", "orgId", "organizationMemberId", "teamFlexLicenceId", "courseKey", "activityType", "topic", "startedAt", "lastHeartbeatAt", "activeSeconds", "lastSequence", "unitsCompleted", "score", "total", "status", "completedAt", "createdAt"], restricted: [] },
  "question-attempts": { readable: ["id", "userId", "examType", "topic", "questionId", "correct", "difficulty", "quizMode", "createdAt", "studentEmail", "sessionId", "confidence", "bookmarked", "orgId", "organizationMemberId", "courseKey", "bankKey", "selectedIndex"], restricted: ["guestToken"] },
  "exam-results": { readable: ["id", "sessionId", "userId", "studentEmail", "examType", "stream", "score", "total", "passed", "timeTakenSeconds", "moduleBreakdown", "createdAt", "province", "calcOnly", "orgId", "organizationMemberId", "courseKey", "bankKey"], restricted: [] },
  "diagnostic-sessions": { readable: ["id", "sessionId", "userId", "studentEmail", "orgId", "organizationMemberId", "courseKey", "correct", "total", "score", "label", "weakTopics", "strongTopics", "topicBreakdown", "completedAt"], restricted: [] },
  "flashcard-progress": { readable: ["id", "email", "examType", "knownIds", "totalCards", "updatedAt"], restricted: [] },
  "flashcard-progress-state": { readable: ["id", "email", "examType", "knownIds", "totalCards"], restricted: [] },
  "flashcard-progress-operations": { readable: ["operationId", "email", "examType", "createdAt"], restricted: ["payloadHash"] },
  "bookmarks": { readable: ["id", "userId", "studentEmail", "bankKey", "questionId", "createdAt"], restricted: [] },
  "qotd-completions": { readable: ["id", "userId", "examType", "questionId", "dateKey", "correct", "createdAt"], restricted: ["guestToken"] },
  "ai-chat-sessions": { readable: ["id", "userId", "examType", "messageCount", "topicsCovered", "sessionStart", "sessionEnd", "studentEmail"], restricted: ["summary", "resourcesSurfaced"] },
  "questions": { readable: ["id", "bankKey", "questionNum", "module", "difficulty", "correctIndex", "isCalc", "topic", "cognitiveLevel", "sourceTitle", "blueprintObjective", "reviewStatus", "reviewedBy", "reviewedAt"], restricted: ["sourceReference", "sourceUrl", "question", "explanation", "steps", "tip", "options"] },
  "question-bank-meta": { readable: ["id", "bankKey", "modules", "moduleTargets", "formulaLinks", "totalQuestions", "contentVersion", "blueprintVersion", "minCalcPerMock", "recallTargetPct"], restricted: [] },
  "question-content-snapshots": { readable: ["id", "releaseKey", "bankKey", "questionId", "questionNum", "sourceContentVersion", "capturedAt"], restricted: ["payload", "contentHash"] },
  "module-overviews": { readable: ["id", "bankKey"], restricted: ["overviewsJson"] },
  "certification-bank-versions": { readable: ["id", "programKey", "bankKey", "versionKey", "blueprintVersion", "releaseChannel", "itemTarget", "active", "commercialEligibility", "teamEligibility", "createdAt", "publishedAt", "retiredAt"], restricted: ["allocationChecksum", "sourceManifestChecksum"] },
  "certification-sources": { readable: ["id", "sourceKey", "publisher", "title", "editionVersion", "retrievedAt", "rightsBasis", "permittedUsage", "verifiedAt"], restricted: ["stableUrl", "sha256"] },
  "certification-blueprint-tasks": { readable: ["id", "bankVersionId", "mwaCode", "taskCode", "title", "officialTarget", "bankTarget", "sourceId"], restricted: ["sourceReference"] },
  "certification-questions": { readable: ["id", "bankVersionId", "bankItemNumber", "taskId", "module", "taskCode", "subtaskCode", "topic", "difficulty", "questionType", "cognitiveLevel", "correctIndex", "isCalc", "diagramId", "diagramAlt", "sourceId", "blueprintObjective", "authorIdentity", "origin", "contentStatus", "publicEligibility", "createdAt", "updatedAt", "retiredAt"], restricted: ["sourceReference", "contentHash", "question", "options", "explanation", "steps", "tip"] },
  "certification-content-reviews": { readable: ["id", "bankVersionId", "contentKind", "contentId", "authorIdentity", "reviewerIdentity", "reviewType", "decision", "reviewedAt"], restricted: ["notes"] },
  "certification-import-runs": { readable: ["id", "bankVersionId", "dryRun", "importerIdentity", "status", "insertedCount", "updatedCount", "rejectedCount", "createdAt", "completedAt"], restricted: ["errorMessage", "manifestChecksum"] },
  "certification-diagrams": { readable: ["id", "bankVersionId", "diagramId", "version", "componentKey", "altText", "sourceId", "authorIdentity", "contentStatus", "retiredAt"], restricted: ["rightsMetadata"] },
  "certification-flashcards": { readable: ["id", "bankVersionId", "taskId", "cardNumber", "sourceId", "authorIdentity", "contentStatus", "retiredAt"], restricted: ["sourceReference", "front", "back"] },
  "certification-module-notes": { readable: ["id", "bankVersionId", "moduleCode", "taskCode", "sourceId", "authorIdentity", "contentStatus", "retiredAt"], restricted: ["sectionsJson", "sourceReference"] },
  "changelog": { readable: ["id", "date", "badge", "badgeColor", "title", "sortOrder", "visible", "createdAt", "updatedAt"], restricted: ["body"] },
  "blog-posts": { readable: ["id", "slug", "title", "excerpt", "author", "tags", "metaTitle", "metaDescription", "readingTimeMinutes", "published", "publishedAt", "createdAt", "updatedAt"], restricted: ["content"] },
  "job-postings": { readable: ["id", "title", "company", "location", "province", "salary", "jobType", "sourceName", "sourceType", "postedAt", "isFeatured", "isActive", "lastSeenAt", "createdAt"], restricted: ["sourceUrl", "description"] },
  "user-feedback": { readable: ["id", "userId", "email", "examType", "rating", "feedbackType", "province", "createdAt"], restricted: ["comment"] },
  "question-error-reports": { readable: ["id", "questionId", "module", "reportType", "createdAt"], restricted: ["questionText", "details"] },
  "trial-emails": { readable: ["id", "email", "source", "createdAt"], restricted: [] },
  "waitlist": { readable: ["id", "email", "courseCode", "courseTitle", "createdAt", "province"], restricted: [] },
  "contact-submissions": { readable: ["id", "name", "email", "createdAt"], restricted: ["subject", "message"] },
  "command-feedback": { readable: ["id", "userId", "scenarioId", "runId", "rating", "createdAt"], restricted: ["guestId", "comment"] },
  "command-email-capture": { readable: ["id", "email", "userId", "source", "createdAt"], restricted: ["guestId"] },
  "product-analytics-events": { readable: ["id", "eventName", "occurredAt", "userId", "examType", "productKey", "orgId"], restricted: ["emailHash", "anonymousHash", "metadata"] },
  "trigger-logs": { readable: ["id", "userId", "triggerType", "sentAt", "cooldownUntil", "studentEmail", "status"], restricted: ["emailSubject", "emailBodyPreview"] },
  "scheduled-work": { readable: ["workKey", "leaseVersion", "status", "leaseUntil", "attempts", "completedAt", "createdAt"], restricted: ["claimToken", "lastError"] },
  "command-drill-queue": { readable: ["id", "userId", "drillName", "queuedAt", "completedAt"], restricted: ["guestId"] },
  "command-run-history": { readable: ["id", "userId", "displayName", "scenarioId", "scenarioTitle", "commandScore", "optimalCalls", "totalSteps", "elapsedSeconds", "completedAt"], restricted: ["guestId", "decisionsJson"] },
  "customer-recovery-evidence": { readable: ["id", "sourceEvidenceKey", "sourceType", "customerEmail", "normalizedEmail", "customerName", "amountMinor", "currency", "paymentStatus", "paymentCreatedAt", "candidateProductKey", "candidateAccessExpiresAt", "reviewStatus", "claimVerifiedAt", "reviewedByUserId", "reviewedAt", "importedPurchaseId", "importedAt", "createdAt", "updatedAt", "recoveryOrganizationName", "recoveryOrganizationGroup", "recoverySeatCount"], restricted: ["sourceArchiveRef", "stripePaymentIntentId", "stripeCheckoutSessionId", "stripeCustomerId", "recoverySubjectType", "reviewNote"] },
  "customer-recovery-batches": { readable: ["id", "recoveryKey", "scriptVersion", "appliedAt", "createdAt", "status"], restricted: ["archiveSha256", "confirmationTokenSha256", "beforeSnapshotSha256", "backupArtifactPath", "planDigest", "outputDigest", "authorizationRef"] },
  "customer-recovery-import-items": { readable: ["id", "batchId", "evidenceId", "organizationId", "managerMemberId", "recoveryGroup", "seatCount", "termStart", "termEnd", "createdAt"], restricted: ["externalReference"] },
};
