import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { build } from "esbuild";
import {
  computeSourceFingerprint,
  isSourceFingerprintPath,
} from "./sourceFingerprint";

export type BuildReleaseKind = "git-commit" | "source-sha256" | "development";
export type BuildReleaseIdentity = {
  release: string;
  releaseKind: BuildReleaseKind;
};
type GitReader = (args: string[]) => string;
// Do not trim the NUL-delimited filenames used for source-membership checks.
const git: GitReader = args =>
  execFileSync("git", args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
const validSha = (value: unknown): value is string =>
  typeof value === "string" && /^(?:[a-f0-9]{40}|[a-f0-9]{64})$/i.test(value);
/** Optional explicit trusted-exporter metadata, not generated by a running server. */
export function archiveReleaseSha(content: string): string {
  const manifest = JSON.parse(content);
  if (
    !manifest ||
    manifest.version !== 1 ||
    manifest.clean !== true ||
    !validSha(manifest.commit)
  )
    throw new Error("Invalid approved release manifest");
  return manifest.commit.toLowerCase();
}

/** Stamp source identity at build time. A source digest is never described as a commit/approval. */
export function buildReleaseIdentity(
  readGit: GitReader = git,
  env: NodeJS.ProcessEnv = process.env,
  readManifest = () =>
    readFileSync(resolve(env.BUILD_RELEASE_FILE ?? "release.json"), "utf8"),
  fingerprint = () => computeSourceFingerprint()
): BuildReleaseIdentity {
  const developmentArtifact = env.BUILD_ARTIFACT_MODE === "development";
  if (env.BUILD_ARTIFACT_MODE !== undefined && !developmentArtifact)
    throw new Error("Unknown build artifact mode");
  if (
    developmentArtifact &&
    (env.NODE_ENV === "production" || env.DEPLOYMENT_ENV === "production")
  )
    throw new Error("Development artifacts cannot be built for production");
  // LAST_COMMIT_HASH is an opaque managed checkpoint label, not commit provenance.
  for (const key of ["BUILD_COMMIT_SHA", "GITHUB_SHA"] as const) {
    if (env[key] !== undefined && !validSha(env[key]))
      throw new Error("Build commit must be a full hexadecimal SHA");
  }
  let sha: string | undefined;
  try {
    sha = readGit(["rev-parse", "--verify", "HEAD"]).trim();
  } catch {
    // A broken/unborn checkout must not silently become a manifest-free archive.
    let checkout = false;
    try {
      checkout =
        readGit(["rev-parse", "--is-inside-work-tree"]).trim() === "true";
    } catch {
      /* no Git source */
    }
    if (checkout || (readGit === git && existsSync(resolve(".git"))))
      throw new Error("Cannot determine checkout HEAD");
  }
  if (sha !== undefined && !validSha(sha))
    throw new Error("Checkout HEAD must be a full hexadecimal SHA");
  if (validSha(sha)) {
    const dirty = readGit([
      "status",
      "--porcelain",
      "--untracked-files=no",
    ]).trim();
    // Root test outputs/private platform metadata do not count. Untracked source does:
    // Git HEAD cannot attest files that bundlers or the runtime may actually consume.
    const extraSource = [
      readGit([
        "ls-files",
        "--others",
        "--directory",
        "--exclude-standard",
        "-z",
      ]),
      readGit([
        "ls-files",
        "--others",
        "--directory",
        "--ignored",
        "--exclude-standard",
        "-z",
      ]),
    ].some(paths =>
      paths
        .split("\0")
        .filter(Boolean)
        .some(path => isSourceFingerprintPath(path.replace(/\/$/, "")))
    );
    if ((dirty || extraSource) && !developmentArtifact)
      throw new Error("Production build requires a clean committed checkout");
    return {
      release: `${sha.toLowerCase()}${dirty || extraSource ? "-dirty" : ""}`,
      releaseKind: dirty || extraSource ? "development" : "git-commit",
    };
  }
  let content: string;
  try {
    content = readManifest();
  } catch (error) {
    if (
      (error as NodeJS.ErrnoException).code !== "ENOENT" ||
      env.BUILD_RELEASE_FILE !== undefined
    ) {
      throw new Error(
        "Invalid or missing explicit archive release provenance",
        { cause: error }
      );
    }
    // Explicit unversioned development behavior is retained, not used by normal publishing.
    if (
      developmentArtifact &&
      env.BUILD_COMMIT_SHA === undefined &&
      env.GITHUB_SHA === undefined
    ) {
      return { release: "development-unversioned", releaseKind: "development" };
    }
    // An environment SHA alone cannot relabel a managed archive as that Git commit.
    const release = fingerprint();
    if (!/^[a-f0-9]{64}$/.test(release))
      throw new Error("Invalid source SHA256 fingerprint");
    return { release, releaseKind: "source-sha256" };
  }
  const commit = archiveReleaseSha(content);
  for (const key of ["BUILD_COMMIT_SHA", "GITHUB_SHA"] as const) {
    if (env[key] !== undefined && env[key]!.toLowerCase() !== commit)
      throw new Error("Archive release SHA mismatch");
  }
  return { release: commit, releaseKind: "git-commit" };
}

/** Kept for callers that only need the identity string; use the kind for comparisons. */
export function buildReleaseId(
  readGit: GitReader = git,
  env: NodeJS.ProcessEnv = process.env,
  readManifest = () =>
    readFileSync(resolve(env.BUILD_RELEASE_FILE ?? "release.json"), "utf8"),
  fingerprint = () => computeSourceFingerprint()
): string {
  return buildReleaseIdentity(readGit, env, readManifest, fingerprint).release;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  const identity = buildReleaseIdentity();
  await build({
    entryPoints: ["server/_core/index.ts"],
    platform: "node",
    packages: "external",
    bundle: true,
    format: "esm",
    outdir: "dist",
    define: {
      __BUILD_RELEASE_ID__: JSON.stringify(identity.release),
      __BUILD_RELEASE_KIND__: JSON.stringify(identity.releaseKind),
    },
    logLevel: "info",
  });
}
