import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { build } from "esbuild";

type GitReader = (args: string[]) => string;
const git: GitReader = args => execFileSync("git", args, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
const validSha = (value: unknown): value is string => typeof value === "string" && /^[a-f0-9]{40}$|^[a-f0-9]{64}$/i.test(value);
/** An archive manifest is generated by the approved clean release exporter, never by a running server. */
export function archiveReleaseSha(content: string): string {
  const manifest = JSON.parse(content);
  if (manifest.version !== 1 || manifest.clean !== true || !validSha(manifest.commit)) throw new Error("Invalid approved release manifest");
  return manifest.commit.toLowerCase();
}
/** Stamp actual source identity. Development/test artifacts require an explicit non-production flag. */
export function buildReleaseId(readGit: GitReader = git, env: NodeJS.ProcessEnv = process.env, readManifest = () => readFileSync(resolve(env.BUILD_RELEASE_FILE ?? "release.json"), "utf8")): string {
  const developmentArtifact = env.BUILD_ARTIFACT_MODE === "development";
  if (developmentArtifact && (env.NODE_ENV === "production" || env.DEPLOYMENT_ENV === "production")) throw new Error("Development artifacts cannot be built for production");
  let sha: string | undefined;
  try { sha = readGit(["rev-parse", "--verify", "HEAD"]); } catch { /* managed archive */ }
  if (sha !== undefined && !validSha(sha)) throw new Error("Checkout HEAD must be a full hexadecimal SHA");
  if (validSha(sha)) {
    const dirty = readGit(["status", "--porcelain", "--untracked-files=no"]).trim();
    if (dirty && !developmentArtifact) throw new Error("Production build requires a clean committed checkout");
    return `${sha.toLowerCase()}${dirty ? "-dirty" : ""}`;
  }
  // A bare environment SHA does not prove which clean source archive was exported.
  const supplied = env.BUILD_COMMIT_SHA ?? env.GITHUB_SHA;
  if (supplied !== undefined && !validSha(supplied)) throw new Error("Build commit must be a full hexadecimal SHA");
  try {
    const commit = archiveReleaseSha(readManifest());
    if (supplied !== undefined && supplied.toLowerCase() !== commit) throw new Error("Archive release SHA mismatch");
    return commit;
  }
  catch (error) {
    if (developmentArtifact && supplied === undefined && !env.BUILD_RELEASE_FILE && (error as NodeJS.ErrnoException).code === "ENOENT") return "development-unversioned";
    throw new Error("Approved archive release provenance is required");
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await build({ entryPoints: ["server/_core/index.ts"], platform: "node", packages: "external", bundle: true, format: "esm", outdir: "dist", define: { __BUILD_RELEASE_ID__: JSON.stringify(buildReleaseId()) }, logLevel: "info" });
}
